num1=int(input("Enter your first number"))
num2=int(input("Enter your second number"))
num3=int(input("Enter your third number"))
print("The sum of the num1 and num2 is : ",num1+num2)
print("The difference when num2 is subtracted from num1 is : ",num2-num1)
print("The product of num1 and num2 is :",num1*num2)
print("The quotient when num1 is divided by num2 is :",num1/num2)
print("The remainder when num1 is divided by num2 is :",num1%num2)
result=((num1+num2)*num3/2)
print("The result of (num1 + num2) * num3 / 2 is :",result)
